config/routes.rb
Rails.application.routes.draw do
  resources :comments

  resources :projects do
    resources :tasks
    resources :memberships
  end

  resources :users

  root "pages#index"
  get "/about" => "pages#about", as: :about
  get "/terms" => "pages#terms", as: :terms
  get "/faq" => "pages#faq", as: :faq

  get '/sign-up' => 'registrations#new', as: :signup
  post '/sign-up' => 'registrations#create'
  get '/sign-in' => 'authentication#new', as: :signin
  post '/sign-in' => 'authentication#create'
  get '/sign-out' => 'authentication#destroy', as: :signout

  post '/projects/:project_id/tasks/:id(.:format)' => 'tasks#create_comment'

  get '/tracker_projects/:tracker_id' => 'projects#tracker_stories', as: :tracker_projects

end

app/models/membership.rb
class Membership < ActiveRecord::Base

  belongs_to :user
  belongs_to :project

  validates :user_id, presence: :true, uniqueness: { scope: :project_id }

  before_destroy :cannot_delete_last_owner
  before_update :cannot_update_last_owner

  def cannot_delete_last_owner
    if owners.count == 1 && self.role == 'Owner'
      return false
    end
  end

  def cannot_update_last_owner
    if owners.count > 1
      return true
    elsif owners.count == 1 && role == 'Member'
      return false
      end
  end

  def owners
    project.memberships.where(role: 'Owner')
  end

  def members
    project.memberships.where(role: 'Member')
  end

  private
end

app/controllers/memberships_controller.rb
class MembershipsController < InternalController

  before_action do
    @project = Project.find(params[:project_id])
  end

  before_action :set_membership, only: [:show, :edit, :update, :destroy]
  before_action :tasks_id_match
  before_action :not_owner_render_404, only: [:new, :create, :update]


  def index
    @membership = @project.memberships.new
    @memberships = @project.memberships.all
  end

  def new
    @membership = @project.memberships.new
  end

  def create
    @membership = @project.memberships.new(membership_params)
    if @membership.save
      redirect_to project_memberships_path(@project), notice: "#{@membership.user.full_name} was added successfully."
    else
      @memberships = @project.memberships.all
      render :index
    end
  end

  def update
    if @membership.update(membership_params)
      redirect_to project_memberships_path(@project), notice: "#{@membership.user.full_name} was updated successfully."
    else
      redirect_to project_memberships_path,
      notice: "You can't change the membership on the last owner."
    end
  end

  def destroy
    if @membership.destroy
      if current_user_has_membership
        redirect_to projects_path,
        notice: "#{@membership.user.full_name} was deleted successfully."
      else
        redirect_to project_memberships_path,
        notice: "#{@membership.user.full_name} was deleted successfully."
      end
    else
      redirect_to project_memberships_path,
      notice: "You are the last person on this project,
        If you want to delete yourself please assign another owner to the project."
    end
  end


  private

  def set_membership
    @membership = @project.memberships.find(params[:id])
  end

  def membership_params
    params.require(:membership).permit(
    :user_id,
    :project_id,
    :role,
    :first_name,
    :last_name,
    )
  end

  def current_user_has_membership
    @membership.user.id == current_user.id
  end

  def not_owner_render_404
    return false if admin?
    if owner?.empty?
      raise AccessDenied
    end
  end

end

app/views/memberships/index.html.erb
<div class="page-header">
  <h1> <%= @project.name %> : Manage Members </h1>
</div>

<ol class="breadcrumb">
  <li><a><%= link_to "Projects", projects_path %> </a></li>
  <li><a> <%= link_to @project.name, project_path(@project) %></a></li>
  <li class= "active">Memberships</li>
</ol>

<div class = "form-horizontal">
  <div class= "form-group">
    <div class = "col-md-5">
      <%= render "shared/errors", instance: @membership %>
    </div>
  </div>
</div>

<% if admin? || !owner?.empty? || !member?%>
  <div class="well form-inline col-md-5 ">
    <%= form_for([@project, @membership], html: {  class: "form-horizonal" }) do |f| %>
      <div class ="form-group">
        <%= f.collection_select(:user_id, User.all, :id, :full_name, {include_blank: "Please select a user..."}, class: "form-control col-md-3 pull-left" ) %>
      </div>
      <div class ="form-group">
        <%= f.select(:role, ["Member", "Owner"], {}, {class: "form-control col-md-3 pull"})%>
      </div>
      <%= f.submit "Add New Member",class: "btn btn-primary pull-right"%>
    <% end %>
  </div>
<%end%>

<br>

<% current_membership = Membership.where(user_id: current_user.id, project_id: @project.id).first %>

<table class = "table">
  <tbody>
    <% @memberships.each do |membership| %>
      <tr>
        <td class="col-sm-2"> <%= link_to membership.user.full_name, user_path(membership.user)%></td>
        <td class="col-sm-2">
          <%= form_for [@project, membership], html: {class: "form-inline"}  do |f| %>
            <% if member?.empty? || admin? %>
              <div class = "form-group">
                <%= f.select(:role, ["Member", "Owner"], {}, {class: "form-control"}) %>
              </div>
              <div class = "form-group">
                <%= f.submit "Update", class: "btn btn-primary "%>
              </div>
            <% else %>
              <div class = "form-group">
                <%= membership.role %>
              </div>
            <% end %>
          <% end %>
        </td>
        <td>
          <% if current_membership && current_membership.role == 'Member' && membership.id == current_membership.id %>
            <%= link_to "", project_membership_path(@project, membership), method: :delete,
              data: {confirm: "Are you Sure?"}, class: "glyphicon glyphicon-remove" %>
          <% elsif (current_membership && current_membership.role == 'Owner' && @memberships.where(role: 'Owner').count > 1) || (current_membership && membership.role == 'Member') %>
            <%= link_to "", project_membership_path(@project, membership), method: :delete,
              data: {confirm: "Are you Sure?"}, class: "glyphicon glyphicon-remove" %>
          <% elsif (admin? && @memberships.where(role: 'Owner').count > 1 && membership.role == 'Owner') %>
            <%= link_to "", project_membership_path(@project, membership), method: :delete,
              data: {confirm: "Are you Sure?"}, class: "glyphicon glyphicon-remove" %>
          <% elsif (admin? && membership.role != 'Owner') %>
            <%= link_to "", project_membership_path(@project, membership), method: :delete,
              data: {confirm: "Are you Sure?"}, class: "glyphicon glyphicon-remove" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>