config/routes.rb
Rails.application.routes.draw do
  resources :comments

  resources :projects do
    resources :tasks
    resources :memberships
  end

  resources :users

  root "pages#index"
  get "/about" => "pages#about", as: :about
  get "/terms" => "pages#terms", as: :terms
  get "/faq" => "pages#faq", as: :faq

  get '/sign-up' => 'registrations#new', as: :signup
  post '/sign-up' => 'registrations#create'
  get '/sign-in' => 'authentication#new', as: :signin
  post '/sign-in' => 'authentication#create'
  get '/sign-out' => 'authentication#destroy', as: :signout

  post '/projects/:project_id/tasks/:id(.:format)' => 'tasks#create_comment'

  get '/tracker_projects/:tracker_id' => 'projects#tracker_stories', as: :tracker_projects

end

app/models/task.rb
class Task < ActiveRecord::Base

  has_many :comments, dependent: :destroy
  belongs_to :project

  validates :description, presence: true 
  validate :due_date_cannot_be_in_the_past, on: :create


  def due_date_cannot_be_in_the_past
    if due_date.present? && due_date < Date.today
      errors.add(:due_date, "can't be in the past")
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < InternalController
  before_action do
    @project = Project.find(params[:project_id])
  end

  before_action :set_task, only: [:show, :edit, :create_comment, :update, :destroy]
  before_action :tasks_id_match

  def index

    @tasks = @project.tasks.where(complete: false).page(params[:page]).per(5)
    @ref = "incomplete"

    if params[:type] =="all"
      @tasks = @project.tasks.page(params[:page]).per(5)
      @ref = "all"
    end

  end


  def show
    @comment = @task.comments.new
    @comments = @task.comments.all
  end


  def new
    @task = @project.tasks.new
  end


  def edit
  end


  def create
    @task = @project.tasks.new(task_params)
    if @task.save
      redirect_to project_tasks_path, notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  def create_comment
    comment_params = params.require(:comment).permit(
    :user_id,
    :task_id,
    :description
    )
    if current_user
      @comment = @task.comments.new(params.require(:comment).merge({:user_id => current_user.id}).permit(:description, :user_id, :task_id))
      @comment.save
      redirect_to project_task_path
    else
      @comment = @task.comments.new
      @comments = @task.comments.all
      render :show
    end
  end

  def update
    @task.update(task_params)
    if @task.save
      redirect_to project_tasks_path, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to project_tasks_path, notice: 'Task was successfully destroyed.'
  end

  private

  def set_task
    @task = @project.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:description, :complete, :due_date)
  end



end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<div class= "form-horizontal">
  <%= form_for [@project, @task] do |f| %>
    <div class = "form-group">
      <div class = "col-sm-offset-2 col-sm-5">
        <%= render "shared/errors", instance: @task %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :description, class: "col-sm-2 control-label" %>
        <div class="col-sm-5">
          <%= f.text_field :description, class: "form-control" %>
        </div>
    </div>

    <div class="form-group">
        <%= f.label :due_date, class: "col-sm-2 control-label" %>
        <div class="col-sm-5">
            <%= f.date_field :due_date, class: "form-control" %>
        </div>
    </div>

    <% unless params[:action] == 'create' || params[:action] == 'new' %>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <div class="checkbox">
            <label><strong><%= f.check_box :complete %>Complete</strong></label>
          </div>
        </div>
      </div>
    <% end %>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-5"> <br>
        <%= f.submit name: button_name, class: "btn btn-primary"%>
      </div>
    </div>
    <br>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<div class="page-header">
  <h1>Editing task</h1>
</div>

<ol class="breadcrumb">
  <li><a><%= link_to "Projects", projects_path %> </a></li>
  <li><a><%= link_to @project.name, project_path(@project) %> </a></li>
  <li><a><%= link_to "Tasks", project_tasks_path %> </a></li>
  <li><a><%= link_to @task.description, project_task_path(@project, @task) %></a></li>
  <li class= "active">Edit</li>
  </ol>

  <%= render 'form', button_name: "Update Task" %>

  <br>
  <br>
  <br>
  <br>
  <br>
</div>

app/views/tasks/index.html.erb
<div class= "page-header">
  <div class= "pull-right">
    <%=link_to_if((@ref == "incomplete"), "All", project_tasks_path(type:"all")) %> |
    <%=link_to_if((@ref == "all"), "Incomplete", project_tasks_path(type:"incomplete")) %>
    <%= link_to 'Create Task', new_project_task_path, class:"btn btn-primary" %>
  </div>
  <h1>Tasks for <%= @project.name %></h1>
</div>

<ol class="breadcrumb">
  <li><a><%= link_to "Projects", projects_path %> </a></li>
  <li><a><%= link_to @project.name, project_path(@project) %> </a></li>
  <li class= "active">Tasks</li>
</ol>

<table class = "table">
  <thead>
    <tr>
      <th>Description</th>
      <th>Complete</th>
      <th>Due</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @project.tasks.each do |task| %>
      <tr>
        <td><%= link_to task.description,project_task_path(task.project, task)  %>
        <span class = "badge"><%= task.comments.count%></span></td>
        <td><%= task.complete %></td>
        <td>
          <% if task.due_date %>
          <%= task.due_date.strftime("%m/%d/%Y") %>
          <% else nil %>
          <%end%>
        </td>
          <td>
            <div class= "pull-right">
              <%= link_to 'Edit', edit_project_task_path(task.project, task), class:"btn btn-info" %>
              <%= link_to "", project_task_path(task.project, task), method: :delete, data: { confirm: 'Are you sure?' },
              class: "glyphicon glyphicon-remove" %>
            </div>
          </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @tasks %>

<br>

app/views/tasks/new.html.erb
<div class="page-header">
  <h1>New Task</h1>
</div>

<div class= "new_task">


  <ol class="breadcrumb">
    <li><a><%= link_to "Projects", projects_path %> </a></li>
    <li><a><%= link_to @project.name, project_path(@project) %> </a></li>
    <li><a><%= link_to "Tasks", project_tasks_path %> </a></li>
    <li class= "active"> New Task</li>
  </ol>

  <%= render 'form', button_name: "Create Task" %>


  <br>
  <br>
  <br>
  <br>
  <br>

</div>

app/views/tasks/show.html.erb
<div class="page-header">
  <h1><%= @task.description%><%= link_to 'Edit', edit_project_task_path(@project,@task), class: "btn btn-info pull-right" %></h1>
</div>

<ol class="breadcrumb">
  <li><a><%= link_to "Projects", projects_path %> </a></li>
  <li><a><%= link_to @project.name, project_path(@project) %> </a></li>
  <li><a><%= link_to "Tasks", project_tasks_path %> </a></li>
  <li class= "active"> <%= @task.description %></li>
</ol>

<p>
  <strong>Complete:</strong>
  <%= @task.complete %>
</p>

<p>
  <strong>Due Date:</strong>
  <% if @task.due_date %>
  <%= @task.due_date.strftime("%m/%d/%Y") %>
  <% else nil %>
  <%end%>
</p>

<h3> Comments </h3>

<% @comments.each do |comment| %>
<div class = "row comments">

  <div class = "col-md-3">
    <% if comment.user_id %>
    <%= link_to comment.user.full_name, user_path(comment.user)%>
    <% else %>
    (deleted user)
    <%end%>
    <div class = "text-muted">
      <%="#{time_ago_in_words(comment.created_at)} ago"%>
    </div>
  </div>
  <div class = "col-md-9">
    <%= comment.description %>
  </div>

</div>
<% end %>

<div class = "row">
  <div class = "col-md-offset-3 col-md-9">
    <%= form_for([@comment], url: {action: "create_comment"}) do |f| %>
    <div class = "form-group">
      <%= f.text_area :description, class:"form-control" %>
    </div>

    <div class = "form-group">
      <%= f.submit "Add Comment", class: "btn btn-primary" %>
    </div>
  </div>
  <%end%>
</div>