config/routes.rb
Rails.application.routes.draw do
  resources :comments

  resources :projects do
    resources :tasks
    resources :memberships
  end

  resources :users

  root "pages#index"
  get "/about" => "pages#about", as: :about
  get "/terms" => "pages#terms", as: :terms
  get "/faq" => "pages#faq", as: :faq

  get '/sign-up' => 'registrations#new', as: :signup
  post '/sign-up' => 'registrations#create'
  get '/sign-in' => 'authentication#new', as: :signin
  post '/sign-in' => 'authentication#create'
  get '/sign-out' => 'authentication#destroy', as: :signout

  post '/projects/:project_id/tasks/:id(.:format)' => 'tasks#create_comment'

  get '/tracker_projects/:tracker_id' => 'projects#tracker_stories', as: :tracker_projects

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  has_many :memberships, dependent: :delete_all
  has_many :users, through: :memberships

  validates :name, presence: true

end

app/controllers/projects_controller.rb
class ProjectsController < InternalController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :project_id_match, except: [:index, :new, :create, :tracker_stories]


  def index
    @projects = Project.all
    tracker_api = TrackerAPI.new
    @tracker_projects = tracker_api.projects(current_user.tracker)
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to project_tasks_path(@project), notice: 'Project was successfully created.'
      Membership.create(project_id: @project.id, user_id: current_user.id, role: "Owner")
    else
      render :new
    end
  end

  def show

  end

  def edit
    unless owner?.present? || admin?
      render 'public/404', status: :not_found, layout: false
    end
  end

  def update
    @project.update(project_params)
    if @project.save
      redirect_to project_path, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    unless owner?.present? || admin?
      render 'public/404', status: :not_found, layout: false
    else
      @project.destroy
      redirect_to projects_path, notice: 'Project was successfully deleted.'
    end
 end

  def tracker_stories
    unless present?
      render 'public/404', status: :not_found, layout: false
    else
      tracker_api = TrackerAPI.new
      @tracker_projects = tracker_api.projects(current_user.tracker)
      @tracker_stories = tracker_api.stories(params[:tracker_id], current_user.tracker)
      @tracker_project = tracker_api.project(params[:tracker_id], current_user.tracker)
    end  
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name)
  end

end

app/views/projects/_form.html.erb
<div class="page-header">
  <h1><%=title%></h1>
</div>

<div class= "form-horizontal">
  <%= form_for(@project) do |f| %>
    <div class = "form-group">
      <div class = "col-sm-offset-2 col-sm-6">
        <%= render "shared/errors", instance: @project %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :name, "Name", class: "col-sm-2 control-label" %>
      <div class="col-sm-4">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-4"> <br>
        <%= f.submit class: "btn btn-primary" %>
      </div>
    </div>
  <%end%>
</div>

app/views/projects/edit.html.erb
<%= render "form", title:"Edit Project"%>

app/views/projects/index.html.erb
<%= page_header "Projects" do %>
  <%= link_to 'Create Project', new_project_path, class:"btn btn-info" %>
<% end %>

<table class = "table">
  <thead>
    <tr>
      <th class = "col-md-2">Name</th>
      <th class = "col-md-2"> Members</th>
      <th class = "col-md-2">Tasks</th>
    </tr>
  </thead>

  <tbody>
    <% if admin? %>
    <% @projects.each do |project| %>
    <tr>
      <td><%= link_to project.name, project_path(project) %></td>
      <td>
        <%= link_to project.memberships.count, project_memberships_path(project)%>
      </td>
      <td><%= link_to project.tasks.count, project_tasks_path(project) %>
      </td>
    </tr>
    <% end %>
    <% else %>
      <% current_user.projects.each do |project| %>
      <tr>
      <td><%= link_to project.name, project_path(project) %></td>
      <td><%= link_to project.memberships.count, project_memberships_path(project)%></td>
      <td><%= link_to project.tasks.count, project_tasks_path(project) %></td>
    </tr>
      <% end %>
      <% end %>
  </tbody>
</table>

<% if current_user.tracker.present? || admin? %>
  <%= page_header "Pivotal Tracker Projects" do %>
  <% end %>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
      </tr>
    </thead>
    <tbody>
      <% @tracker_projects.each do |project| %>
      <tr>
        <td><%= link_to project[:name], tracker_projects_path(tracker_id: project[:id]) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <% end %>

app/views/projects/new.html.erb
<%= render "form", title:"Create Project"%>

app/views/projects/show.html.erb
<div class= "page-header">
  <div class= "pull-right">
    <% if owner?.present? || admin? %>
      <%= link_to 'Edit', edit_project_path(@project), class: "btn btn-info" %>
    <%end%>


  </div>
  <h1><strong><%= @project.name %></strong></h1>
</div>
<div class = "form-group">
<ol class="breadcrumb">
  <li><a><%= link_to "Projects", projects_path %> </a></li>
  <li class= "active"> <%= @project.name %></li>
</ol>

<%= link_to (pluralize(@project.tasks.count, "Task")), project_tasks_path(@project, @tasks) %>

<br>

<%= link_to (pluralize(@project.memberships.count,"Member")), project_memberships_path(@project) %>
</div>
 <% if owner?.present? || admin? %>
<div class="well form-inline col-sm-7">
    <div class="form-group">
      <strong>Delete Project</strong>
      <p>Deleting this project will also delete <%= pluralize(@project.memberships.count, "Membership") %>,
         <%= pluralize(@project.tasks.count, "Task") %> and associated comments.</p>
      <%= link_to 'Delete', @project, method: :delete, data: { confirm: 'Are you sure?' },
          class: "btn btn-danger" %>
    </div>
  </div>
<%end%>

app/views/projects/tracker_stories.html.erb
<%= page_header "Stories for #{@tracker_project[:name]}" do %>
<p>(showing first 500)</p>
<% end %>

<table class="table table-striped table-bordered">
  <thead>
    <tr class= "active">
      <th>Story</th>
      <th>
        Estimate
      </th>
      <th>
        Labels
      </th>
      <th>
        Current State
      </th>
    </tr>
  </thead>
  <tbody>
    <% @tracker_stories.each do |story| %>
    <tr>
      <td><%= link_to story[:name], 'http://www.pivotaltracker.com'  %> </td>
      <td>
        <%= story[:estimate] %>
      </td>
      <td>
        <% @labels = [] %>
        <% story[:labels].each do |label| %>
        <% @labels << label[:name] %>
        <% end %>
        <%= @labels.join(", ") %>
      </td>
      <td>
        <%= story[:current_state] %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>