config/routes.rb
Rails.application.routes.draw do
  resources :comments

  resources :projects do
    resources :tasks
    resources :memberships
  end

  resources :users

  root "pages#index"
  get "/about" => "pages#about", as: :about
  get "/terms" => "pages#terms", as: :terms
  get "/faq" => "pages#faq", as: :faq

  get '/sign-up' => 'registrations#new', as: :signup
  post '/sign-up' => 'registrations#create'
  get '/sign-in' => 'authentication#new', as: :signin
  post '/sign-in' => 'authentication#create'
  get '/sign-out' => 'authentication#destroy', as: :signout

  post '/projects/:project_id/tasks/:id(.:format)' => 'tasks#create_comment'

  get '/tracker_projects/:tracker_id' => 'projects#tracker_stories', as: :tracker_projects

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>gCamp</title>

  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>

</head>

<body style= "padding-top:60px"<% if request.path == '/' %> class="full" <% end %>>

  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <a class="navbar-brand" href="/">gCamp</a>
      <ul class= "nav navbar-nav navbar-right">
        <% if current_user %>
        <li><%= link_to ("#{current_user.first_name} #{current_user.last_name}"),
        user_path(current_user) %></li>
        <li><%= link_to "Sign Out", signout_path %></li>
        <% else %>
        <li><%= link_to "Sign Up", signup_path %></li>
        <li><%= link_to "Sign In", signin_path %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class= "container">
    <% if notice %>
    <div class= "alert alert-success text-center" role= "alert">
      <strong><p> <%= notice %></p></strong>
    </div>
    <% end %>
    <%= yield %>
  </div>

  <hr>

  <div class ="footer">
    <footer class= "container">
      <div>
        <div class= "col-md-5">
          <%= link_to "About |", about_path %> <%= link_to "Terms |", terms_path%> <%= link_to "FAQ ",
          faq_path %>
          <% if current_user %>
          <%= link_to("| My Projects", projects_path) %>
          <%end%>
        </div>
        <div class= "col-md-offset-9">
          <%= link_to "https://www.linkedin.com/profile/view?id=248387462&trk=nav_responsive_tab_profile" do %>
          <%= image_tag("linked_in.jpg") %>
          <%end%> |

          <%= link_to "https://github.com/Geekyflamingo" do %>
          <%= image_tag("GitHub.png") %>
          <%end%> |

          <%= link_to "https://twitter.com/Geekyflamingo" do %>
          <%= image_tag("Twitter.png") %>
          <%end%> |

          <%= link_to "http://www.galvanize.it/school/" do %>
          <%= image_tag("gschool.png") %>
          <%end%>
        </div>
      </div>
    </footer>
  </div>

  <%= javascript_include_tag 'application' %>
</body>
</html>

app/views/layouts/internal.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title><%= "gCamp #{content_for(:title)}" %></title>

  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
</head>

<body style= "padding-top:60px"<% if request.path == '/' %> class="full" <% end %>>

  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <a class="navbar-brand" href="/projects">gCamp</a>
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            My Projects
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <% if admin? %>
              <% @projects.each do |project| %>
                <li> <%= link_to project.name, project_path(project) %> </li>
            <% end %>
            <% else %>
               <% current_user.projects.each do |project| %>
                <li> <%= link_to project.name, project_path(project) %> </li>
                <% end %>
            <% end %>
            <li class="divider"></li>
            <li><%= link_to "New Project", new_project_path %></li>
          </ul>
        </li>
        <li>
          <%= link_to "Users", users_path %>
        </li>
      </ul>
      <ul class= "nav navbar-nav navbar-right">
        <% if current_user %>
        <li><%= link_to ("#{current_user.first_name} #{current_user.last_name}"),
        user_path(current_user) %></li>
        <li><%= link_to "Sign Out", signout_path %></li>
        <% else %>
        <li><%= link_to "Sign Up", signup_path %></li>
        <li><%= link_to "Sign In", signin_path %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class= "container">
    <% if notice %>
    <div class= "alert alert-success text-center" role= "alert">
      <strong><p> <%= notice %></p></strong>
    </div>
    <% end %>
    <%= yield %>
  </div>

  <hr>

  <div class ="footer">
    <footer class= "container">
      <div>
        <div class= "text-center">
          <%= link_to "Home |",
          root_path %> <%= link_to "About |", about_path %> <%= link_to "Terms |", terms_path%> <%= link_to "FAQ ",
          faq_path %>
        </div>
      </div>
    </footer>
  </div>


</body>
</html>